import StyledComponentsRegistry from "@/lib/antdRegistery";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import MainLayout from "./mainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
            <MainLayout>
              {children}
            </MainLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
